"""
Planner Schemas — Milestone 10

This module defines the strongly-typed ExecutionPlan and all its supporting
models. The ExecutionPlan is the ONLY output of the Planner. It is NEVER
generated by the Executor or any other component.

Design Contract:
    - The Planner produces an ExecutionPlan.
    - The Plan Validator (Pydantic) validates it before Executor receives it.
    - The Executor may correct obvious tool mismatches before execution
      (e.g. DOCUMENT_SUMMARY planned with search → swap to reader).
    - Future tools (Gmail, GitHub, etc.) can be added to ToolEnum without
      changing any Executor logic.
"""

from __future__ import annotations

import uuid
from enum import Enum
from typing import Any, Dict, List, Literal, Optional

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Enumerations
# ---------------------------------------------------------------------------

class TaskType(str, Enum):
    """Top-level classification of what the user wants to accomplish."""

    DOCUMENT_SUMMARY = "DOCUMENT_SUMMARY"
    """Summarise an entire attached document."""

    DOCUMENT_QA = "DOCUMENT_QA"
    """Answer a factual question from attached documents (semantic retrieval)."""

    DOCUMENT_COMPARISON = "DOCUMENT_COMPARISON"
    """Compare or contrast two or more attached documents."""

    DOCUMENT_SEARCH = "DOCUMENT_SEARCH"
    """Search documents for a concept, term, or entity."""

    DOCUMENT_EXTRACTION = "DOCUMENT_EXTRACTION"
    """Extract structured data (tables, lists, fields) from documents."""

    DOCUMENT_TRANSLATION = "DOCUMENT_TRANSLATION"
    """Translate document content into a different language."""

    DOCUMENT_REWRITE = "DOCUMENT_REWRITE"
    """Improve, rephrase, or reformat document content."""

    GENERAL = "GENERAL"
    """Answer using general LLM knowledge without documents."""

    HYBRID = "HYBRID"
    """Combine document knowledge with general LLM expertise."""

    CONVERSATION_MEMORY = "CONVERSATION_MEMORY"
    """Query refers to earlier parts of the conversation."""

    UNKNOWN = "UNKNOWN"
    """Fallback when the planner cannot determine intent."""


class ToolName(str, Enum):
    """
    Canonical names for all registered tools.

    Future tools (Gmail, GitHub, Calendar…) are added here only.
    The Executor and Tool Registry are designed so that adding a new
    ToolName requires ZERO changes to Executor logic.
    """

    DOCUMENT_READER = "document_reader"
    """Load and read the full text of one or more attached documents."""

    DOCUMENT_SEARCH = "document_search"
    """Semantically search attached documents via embeddings + Qdrant."""

    GENERAL_LLM = "general_llm"
    """Invoke the LLM directly without any document context."""

    CONVERSATION_MEMORY = "conversation_memory"
    """Retrieve recent conversation history from the database."""

    # -----------------------------------------------------------------------
    # Future tools (not yet implemented but registered here for planning)
    # -----------------------------------------------------------------------
    # GMAIL = "gmail"
    # GOOGLE_DRIVE = "google_drive"
    # GITHUB = "github"
    # CALENDAR = "calendar"
    # WEB_SEARCH = "web_search"
    # PYTHON_EXECUTOR = "python_executor"
    # PDF_GENERATOR = "pdf_generator"


class RetrievalStrategy(str, Enum):
    """How the DocumentSearch tool should retrieve chunks."""

    SEMANTIC = "semantic"
    """Pure vector similarity search."""

    HYBRID = "hybrid"
    """Vector similarity + keyword BM25 (future)."""

    FULL_DOCUMENT = "full_document"
    """Load entire document(s) sequentially (used by DocumentReader)."""


class ResponseMode(str, Enum):
    """Controls how the final answer is generated."""

    STREAM = "stream"
    """Stream tokens to the client as they are generated."""

    FULL = "full"
    """Collect the full response before sending."""


# ---------------------------------------------------------------------------
# Step Model
# ---------------------------------------------------------------------------

class ExecutionStep(BaseModel):
    """
    A single step in the execution plan.

    The Executor iterates over these steps in order (unless parallel=True).
    Each step corresponds to exactly one registered tool.
    """

    step_id: str = Field(
        default_factory=lambda: uuid.uuid4().hex[:8],
        description="Unique identifier for this step within the plan."
    )
    tool: ToolName = Field(
        description="The tool to invoke for this step."
    )
    description: str = Field(
        default="",
        description="Human-readable description of what this step does."
    )
    config: Dict[str, Any] = Field(
        default_factory=dict,
        description="Tool-specific configuration passed at runtime."
    )
    parallel: bool = Field(
        default=False,
        description="If True, this step runs concurrently with other parallel steps."
    )
    depends_on: List[str] = Field(
        default_factory=list,
        description="List of step_ids that must complete before this step runs."
    )
    retry_on_failure: bool = Field(
        default=True,
        description="Whether to retry this step once on transient failure."
    )


# ---------------------------------------------------------------------------
# Execution Plan
# ---------------------------------------------------------------------------

class ExecutionPlan(BaseModel):
    """
    The authoritative, strongly-typed output of the Planner.

    This model is the ONLY interface between the Planner and the Executor.
    It must be Pydantic-validated before the Executor receives it.

    Design invariants:
        - Planner populates this. Executor reads it. Nobody else touches it.
        - steps are executed in order unless individual steps set parallel=True.
        - rewritten_query, if present, overrides the raw user query for retrieval.
    """

    # Identity
    plan_id: str = Field(
        default_factory=lambda: f"plan_{uuid.uuid4().hex[:8]}",
        description="Unique identifier for this plan (used for observability)."
    )
    planner_version: str = Field(
        default="2.0.0",
        description="Version of the planner that generated this plan."
    )

    # Intent & Reasoning (for observability, not for Executor logic)
    task: TaskType = Field(
        description="High-level classification of the user request."
    )
    reasoning: str = Field(
        default="",
        description="The planner's natural-language justification for this plan."
    )
    confidence: float = Field(
        default=1.0,
        ge=0.0,
        le=1.0,
        description="Planner's confidence in this plan (0.0–1.0)."
    )

    # Execution Steps (the actual work to be done)
    steps: List[ExecutionStep] = Field(
        default_factory=list,
        description="Ordered list of tool invocations to execute."
    )

    # Query rewriting
    rewritten_query: Optional[str] = Field(
        default=None,
        description="Query optimised for vector search (null = use raw query)."
    )

    # Resource requirements (allows Executor to pre-validate before running)
    requires_documents: bool = Field(
        default=False,
        description="True if any step needs attached documents."
    )
    requires_retrieval: bool = Field(
        default=False,
        description="True if any step performs semantic retrieval."
    )
    requires_history: bool = Field(
        default=False,
        description="True if any step needs conversation history."
    )
    requires_general_knowledge: bool = Field(
        default=False,
        description="True if any step uses LLM general knowledge."
    )

    # Response configuration
    response_mode: ResponseMode = Field(
        default=ResponseMode.STREAM,
        description="Whether to stream or return the full response."
    )
    output_format: Optional[str] = Field(
        default=None,
        description="Desired output format (markdown, json, plain, etc.)."
    )

    # Retrieval configuration (populated from step config, but hoisted for Executor convenience)
    retrieval_strategy: Optional[RetrievalStrategy] = Field(
        default=None,
        description="Retrieval strategy used for DocumentSearch steps."
    )
    document_scope: Optional[str] = Field(
        default=None,
        description="Filter to a specific document title or provider."
    )
    max_chunks: int = Field(
        default=5,
        ge=1,
        le=20,
        description="Maximum number of chunks to retrieve."
    )
    answer_length: Literal["short", "medium", "detailed"] = Field(
        default="medium",
        description="Response verbosity: short | medium | detailed (default medium).",
    )

    # Fallback metadata
    is_fallback: bool = Field(
        default=False,
        description="True if this plan was generated by the fallback path."
    )
    fallback_reason: Optional[str] = Field(
        default=None,
        description="Why the fallback plan was used (if is_fallback=True)."
    )


# ---------------------------------------------------------------------------
# Planner Request
# ---------------------------------------------------------------------------

class PlannerRequest(BaseModel):
    """Input to the PlannerService. Internal only — never from the client."""

    query: str = Field(description="The raw user query.")
    conversation_id: str = Field(description="UUID of the current conversation.")
    has_documents: bool = Field(
        default=False,
        description="Whether the conversation has attached documents."
    )
    attached_document_titles: List[str] = Field(
        default_factory=list,
        description="Titles of attached documents (for planner context)."
    )
    attached_documents_metadata: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="Complete metadata for attached documents (mime_type, size, provider)."
    )
    conversation_history: List[Dict[str, str]] = Field(
        default_factory=list,
        description="Recent conversation history (roles and messages) for context."
    )
    execution_context_summary: Dict[str, Any] = Field(
        default_factory=dict,
        description="Summary of current execution state, user, and configurations."
    )
    response_mode_override: Optional[str] = Field(
        default=None,
        description="If set by the API request, overrides the planner's response_mode."
    )
