"""Update Document storage architecture

Revision ID: 04377c88f642
Revises: ba2d68a875f6
Create Date: 2026-07-13 15:39:55.180234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04377c88f642'
down_revision: Union[str, None] = 'ba2d68a875f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('storage_path', sa.String(length=1024), nullable=True))
    op.add_column('documents', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('checksum', sa.String(length=255), nullable=True))
    op.alter_column('documents', 'mime_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_column('documents', 'raw_content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('raw_content', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.alter_column('documents', 'mime_type',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('documents', 'checksum')
    op.drop_column('documents', 'file_size')
    op.drop_column('documents', 'storage_path')
    # ### end Alembic commands ###
