"""add_credentials_to_integration

Revision ID: 541b05c37faf
Revises: d87fceb2d49b
Create Date: 2026-07-13 13:48:22.317251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '541b05c37faf'
down_revision: Union[str, None] = 'd87fceb2d49b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integrations', sa.Column('credentials', sa.JSON(), nullable=True))
    op.add_column('integrations', sa.Column('settings', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('integrations', 'settings')
    op.drop_column('integrations', 'credentials')
    # ### end Alembic commands ###
