"""Update Integration to belong to User instead of Workspace

Revision ID: b2fe4a43cd33
Revises: 541b05c37faf
Create Date: 2026-07-13 13:59:28.438033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2fe4a43cd33'
down_revision: Union[str, None] = '541b05c37faf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integrations', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.drop_index(op.f('ix_integrations_workspace_id'), table_name='integrations')
    op.create_index(op.f('ix_integrations_user_id'), 'integrations', ['user_id'], unique=False)
    op.drop_constraint(op.f('integrations_workspace_id_fkey'), 'integrations', type_='foreignkey')
    op.create_foreign_key(None, 'integrations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('integrations', 'workspace_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integrations', sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'integrations', type_='foreignkey')
    op.create_foreign_key(op.f('integrations_workspace_id_fkey'), 'integrations', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_integrations_user_id'), table_name='integrations')
    op.create_index(op.f('ix_integrations_workspace_id'), 'integrations', ['workspace_id'], unique=False)
    op.drop_column('integrations', 'user_id')
    # ### end Alembic commands ###
