"""document import pipeline

Revision ID: ce2719d95d89
Revises: b2fe4a43cd33
Create Date: 2026-07-13 15:10:03.569002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce2719d95d89'
down_revision: Union[str, None] = 'b2fe4a43cd33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.add_column('documents', sa.Column('provider', sa.String(length=50), nullable=False))
    op.add_column('documents', sa.Column('external_id', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('mime_type', sa.String(length=50), nullable=False))
    op.add_column('documents', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('documents', sa.Column('raw_content', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('processed_content', sa.String(), nullable=True))
    op.drop_index(op.f('ix_documents_processing_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_workspace_id'), table_name='documents')
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.drop_constraint(op.f('documents_workspace_id_fkey'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('documents', 'external_document_id')
    op.drop_column('documents', 'workspace_id')
    op.drop_column('documents', 'file_type')
    op.drop_column('documents', 'processing_status')
    op.drop_column('documents', 'source_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('source_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('processing_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('file_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('external_document_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('documents_workspace_id_fkey'), 'documents', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.create_index(op.f('ix_documents_workspace_id'), 'documents', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_documents_processing_status'), 'documents', ['processing_status'], unique=False)
    op.drop_column('documents', 'processed_content')
    op.drop_column('documents', 'raw_content')
    op.drop_column('documents', 'status')
    op.drop_column('documents', 'mime_type')
    op.drop_column('documents', 'external_id')
    op.drop_column('documents', 'provider')
    op.drop_column('documents', 'user_id')
    # ### end Alembic commands ###
